export const kategori = [
  {
    name: "HOME CARE",
    id: 1,
  },
  {
    name: "LAMPU JALAN",
    id: 2,
  },
  {
    name: "PENGADUAN PLN",
    id: 3,
  },
  {
    name: "AMBULANS JENAZAH",
    id: 4,
  },
  {
    name: "ANJAL, TERLANTAR, PENGEMIS DAN GEPENG",
    id: 5,
  },
  {
    name: "BANJIR",
    id: 6,
  },
  {
    name: "BENCANA ALAM",
    id: 7,
  },
  {
    name: "COVID - 19",
    id: 8,
  },
  {
    name: "DRAINASE",
    id: 9,
  },
  {
    name: "EVAKUASI HEWAN LIAR",
    id: 10,
  },
  {
    name: "FOGGING DBD",
    id: 11,
  },
  {
    name: "KEAMANAAN DAN KETERTIBAN UMUM / MASYARAKAT",
    id: 12,
  },
  {
    name: "KEBAKARAN",
    id: 13,
  },
  {
    name: "KECELAKAAN",
    id: 14,
  },
  {
    name: "KEKERASAN PEREMPUAN/ANAK/KDRT",
    id: 15,
  },
  {
    name: "KELURAHAN",
    id: 16,
  },
  {
    name: "KERUMUNAN",
    id: 17,
  },
  {
    name: "KERUSUHAN/TAWURAN",
    id: 18,
  },
  {
    name: "KRIMINALITAS",
    id: 19,
  },
  {
    name: "ORANG DENGAN GANGGUAN JIWA (ODGJ)",
    id: 20,
  },
  {
    name: "PARKIR LIAR",
    id: 21,
  },
  {
    name: "PENGADUAN PDAM",
    id: 22,
  },
  {
    name: "PERMASALAHAN JALAN RAYA",
    id: 23,
  },
  {
    name: "PERMASALAHAN SAMPAH",
    id: 24,
  },
  {
    name: "POHON TUMBANG",
    id: 25,
  },
  {
    name: "PROTOKOL KESEHATAN",
    id: 26,
  },
  {
    name: "SEDOT TINJA",
    id: 27,
  },
];

export const kecamatan = [
  {
    id: 1,
    nama: "MARISO",
    kelurahan: [
      "BONTORANNU",
      "TAMARUNANG",
      "MATTOANGIN",
      "KAMPUNG BUYANG",
      "MARISO",
      "MARION",
      "PANAMBUNGAN",
      "KUNJUNG MAE",
    ],
  },
  {
    id: 2,
    nama: "MAMAJANG",
    kelurahan: [
      "TAMPARANG KEKE",
      "SAMBUNG JAWA",
      "KARANG ANYAR",
      "BAJI MAPPAKASUNGGU",
      "PA'BATANG",
      "PARANG",
      "BONTO LEBANG",
      "MAMAJANG DALAM",
      "LABUANG BAJI",
      "BONTO BIRAENG",
      "MANDALA",
      "MARICAYA SELATAN",
      "MAMAJANG LUAR",
    ],
  },
  {
    id: 3,
    nama: "TAMALATE",
    kelurahan: [
      "BAROMBONG",
      "TANJUNG MERDEKA",
      "MACCINI SOMBALA",
      "BALANG BARU",
      "JONGAYA",
      "BONGAYA",
      "PA'BAENG-BAENG",
      "MANNURUKI",
      "PARANG TAMBUNG",
      "MANGASA",
      "BONTO DURI",
    ],
  },
  {
    id: 4,
    nama: "RAPPOCINI",
    kelurahan: [
      "GUNUNG SARI",
      "KARUNRUNG",
      "MAPPALA",
      "KASSI-KASSI",
      "BONTO MAKKIO",
      "TIDUNG",
      "BANTA-BANTAENG",
      "BUAKANA",
      "RAPOCCINI",
      "BALLAPARANG",
      "MINASA UPA",
    ],
  },
  {
    id: 5,
    nama: "MAKASSAR",
    kelurahan: [
      "MARICAYA",
      "MARICAYA BARU",
      "MARADEKAYA SELATAN",
      "BARA-BARAYA SELATAN",
      "BARA-BARAYA",
      "MARADEKAYA",
      "MARADEKAYA UTARA",
      "BARA-BARAYA UTARA",
      "BARA-BARAYA TIMUR",
      "MACCINI PARANG",
      "MACCINI",
      "MACCINI GUSUNG",
      "BARANA",
      "LARIANG BANGI",
    ],
  },
  {
    id: 6,
    nama: "UJUNG PANDANG",
    kelurahan: [
      "LAE-LAE",
      "LOSARI",
      "MANGKURA",
      "PISANG SELATAN",
      "LAJANGIRU",
      "SAWERIGADING",
      "MALOKU",
      "BULOGADING",
      "BARU",
      "PISANG UTARA",
    ],
  },
  {
    id: 7,
    nama: "WAJO",
    kelurahan: [
      "PATTUNUANG",
      "MELAYU BARU",
      "MELAYU",
      "MAMPU",
      "MALIMONGAN",
      "MALIMONGAN TUA",
    ],
  },
  {
    id: 8,
    nama: "BONTOALA",
    kelurahan: [
      "GADDONG",
      "WAJO BARU",
      "TOMPO BALANG",
      "MALIMONGAN BARU",
      "TIMUNGAN LOMPOA",
      "BARAYA",
      "BONTOALA",
      "BONTOALA PARANG",
      "BONTOALA TUA",
      "BUNGA EJAYA",
      "LAYANG",
      "PARANG LAYANG",
    ],
  },
  {
    id: 9,
    nama: "UJUNG TANAH",
    kelurahan: [
      "UJUNG TANAH",
      "TAMALABBA",
      "TABARINGAN",
      "TOTAKA",
      "PATTINGALLOANG",
      "PATTINGALLOANG BARU",
      "CAMBA BERUA",
      "CAMBAYA",
    ],
  },
  {
    id: 10,
    nama: "KEPULAUAN SANGKARRANG",
    kelurahan: ["KODINGARENG", "BARRANG CADDI", "BARRANG LOMPO"],
  },
  {
    id: 11,
    nama: "TALLO",
    kelurahan: [
      "BUNGA EJA BERU",
      "LEMBO",
      "KALUKUANG",
      "LA'LATANG",
      "RAPPOJAWA",
      "TAMMUA",
      "RAPOKALLING",
      "WALA-WALAYA",
      "UJUNG PANDANG BARU",
      "SUWANGGA",
      "PANNAMPU",
      "KALUKU BODOA",
      "BULOA",
      "TALLO",
      "LAKKANG",
    ],
  },
  {
    id: 12,
    nama: "PANAKKUKANG",
    kelurahan: [
      "PAROPO",
      "KARAMPUANG",
      "PANDANG",
      "MASALE",
      "TAMAMAUNG",
      "KARUWISI",
      "SINRI JALA",
      "KARUWISI UTARA",
      "PAMPANG",
      "PANAIKANG",
      "TELLO BARU",
    ],
  },
  {
    id: 13,
    nama: "MANGGALA",
    kelurahan: [
      "BORONG",
      "BANGKALA",
      "TAMANGAPA",
      "MANGGALA",
      "ANTANG",
      "BATUA",
      "BITOWA",
      "BIRING ROMANG",
    ],
  },
  {
    id: 14,
    nama: "BIRING KANAYA",
    kelurahan: [
      "PACCERAKKANG",
      "DAYA",
      "P A I",
      "SUDIANG RAYA",
      "SUDIANG",
      "BULUROKENG",
      "UNTIA",
      "BERUA",
      "KATIMBANG",
      "BAKUNG",
      "LAIKANG",
    ],
  },
  {
    id: 15,
    nama: "TAMALANREA",
    kelurahan: [
      "TAMALANREA INDAH",
      "TAMALANREA JAYA",
      "TAMALANREA",
      "KAPASA",
      "PARANG LOE",
      "BIRA",
      "KAPASA RAYA",
    ],
  },
];

export const phone = [
  {
    id: 1,
    kategori: "Kategori 1",
    nama: "Nama 1",
    wilayah: "Wilayah 1",
    alamat:
      "https://www.google.com/maps/place/Makassar,+Kota+Makassar,+Sulawesi+Selatan/@-5.1114743,119.2625408,11z/data=!3m1!4b1!4m5!3m4!1s0x2dbee329d96c4671:0x3030bfbcaf770b0!8m2!3d-5.1476651!4d119.4327314",
    telp: "Telp 1",
    alternatif: "Alternatif 1",
    updated_at: "Updated 1",
  },
  {
    id: 2,
    kategori: "Kategori 1",
    nama: "Nama 1",
    wilayah: "Wilayah 1",
    alamat: "Alamat 1",
    telp: "Telp 1",
    updated_at: "Updated 1",
  },
  {
    id: 3,
    kategori: "Kategori 1",
    nama: "Nama 1",
    wilayah: "Wilayah 1",
    alamat: "Alamat 1",
    telp: "Telp 1",
    alternatif: "Alternatif 1",
    updated_at: "Updated 1",
  },
];
