name: deploy

on:
  push:
    branches: [deploy]

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and deploy node app
        uses: appleboy/ssh-action@master
        env:
         FOO: ${{ secrets.SSH_PASSWORD }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/makassar112
            sudo su
            $FOO
            git pull https://${{ secrets.TOKEN }}@github.com/Dinel13/makassar112.git deploy